services:
  - type: web
    name: idea-submission-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/lee-sillah/IdeaSubmissionForm.js/edit/main/render.yaml
    branch: main  
